import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header style={{

          display: "flex",
          backgroundColor: "ghostwhite",
          padding: "1rem",
        }}>
          <ul style={{
            display: "flex",
            flexDirection: "row",
            margin: "1vh"
          }}>
            <li>
              <a style={{ margin: "2rem" }} href="">About  </a>
            </li>
            <li><a style={{ margin: "2rem" }} href="">contact </a></li>
            <li><a style={{ margin: "2rem" }} href="">Info </a></li>
          </ul>


        </header>

        {children}</body>
    </html>
  );
}
